In [8]:
import numpy as np

A=np.array([[24,27,3,48],
           [41,2,58.2,64.5],
           [75.8,104.4,24,8.1]])
print(A)

[[ 24.   27.    3.   48. ]
 [ 41.    2.   58.2  64.5]
 [ 75.8 104.4  24.    8.1]]


In [9]:
cal=A.sum(axis=0) #sums up the matrix vertically by coloumns
print(cal)

[140.8 133.4  85.2 120.6]


In [13]:
p=100*A/cal
print(p) 

[[17.04545455 20.23988006  3.52112676 39.80099502]
 [29.11931818  1.49925037 68.30985915 53.48258706]
 [53.83522727 78.26086957 28.16901408  6.71641791]]
